### ISSUE TITLE
怎么用？

### ISSUE THREAD

**Issue by AntJavascript** [Simon-Bin/flant#4]
没有使用例子吗？怎么引入？

**Comment by Binbiubiubiu** [comment]
``` yaml
flant:
    git:
      url: https://github.com/Binbiubiubiu/flant.git
```
可以这样引入,
这个项目我个人暂时不维护了,也不建议商业项目使用. 如果需要flutter组件库可以看看贝壳的 https://bruno.ke.com/
